echo "Cleaning repo first.."
rm -rf dist
rm -rf build
rm -rf colourmap.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf colourmap/__pycache__
rm -rf colourmap/.pylint.d
rm -rf colourmap/tests/__pycache__
rm -rf tests/__pycache__
rm -rf colourmap/utils/__pycache__
rm -rf .pylint.d
rm -rf colourmap/data/*.zip
rm -rf colourmap/data/*.csv
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf .coverage*
rm -rf .pkl
rm -rf colourmap.egg-info